version: "3.9"

services:
  trainer:
    build:
      context: .
      dockerfile: dockerfiles/train_model.dockerfile
    image: diabetes_trainer:latest
    volumes:
      - ./models:/workspace/models
      - ./data:/workspace/data
      - ./configs:/workspace/configs
    working_dir: /workspace

  predict:
    build:
      context: .
      dockerfile: dockerfiles/predict_model.dockerfile
    image: diabetes_predict:latest
    depends_on:
      - trainer
    volumes:
      - ./models:/workspace/models
      - ./data:/workspace/data:ro
    ports:
      - "8000:8000"
    working_dir: /workspace
