version: "3.9"

services:
  trainer:
    build:
      context: .
      dockerfile: dockerfiles/train_model.dockerfile
    image: diabetes_trainer:latest
    volumes:
      - ./models:/workspace/models
      - ./data:/workspace/data
      - ./.dvc:/workspace/.dvc
      - ./.git:/workspace/.git:ro
      - dvc_cache:/root/.cache/dvc
      - ./client_secrets.json:/workspace/client_secrets.json:ro
    working_dir: /workspace

  predict:
    build:
      context: .
      dockerfile: dockerfiles/predict_model.dockerfile
    image: diabetes_predict:latest
    depends_on:
      - trainer
    volumes:
      - ./models:/workspace/models
      - ./data:/workspace/data:ro
      - ./.dvc:/workspace/.dvc
      - ./.git:/workspace/.git:ro
      - dvc_cache:/root/.cache/dvc:ro
      - ./client_secrets.json:/workspace/client_secrets.json:ro
    ports:
      - "8000:8000"
    working_dir: /workspace

volumes:
  dvc_cache:
