name: CML Model Training Report

on: [pull_request]

jobs:
  cml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install dvc[gs] cml

      - name: Train model and capture metrics
        run: |
          python src/train_model.py > metrics.txt

      - name: Create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "## Model Training Metrics" > report.md
          cat metrics.txt >> report.md
          cml comment create report.md
