name: CML Model Training Report
on:
  pull_request:
      branches: 
        - main
permissions:
  contents: write
  pull-requests: write
jobs:
  cml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: iterative/setup-cml@v1

      - name: Train model and create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python src/train_model.py > metrics.txt

          echo "## Model Training Metrics" > report.md
          cat metrics.txt >> report.md

          # If you generate a plot:
          # cml publish plot.png --md >> report.md

          cml comment create --target=pr --publish report.md
