name: CML Model Training Report
on:
  pull_request:
      branches: 
        - main
permissions:
  contents: write
  pull-requests: write
jobs:
  cml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - uses: iterative/setup-cml@v1

      - name: Train model and create CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install --upgrade pip
          pip install dvc[gs]
          pip install -r requirements.txt

          echo "Running model training..."
          python -m diabetes_predictor.train_model > metrics.txt

          echo "## Model Training Metrics" > report.md
          cat metrics.txt >> report.md

          echo "Report contents:"
          cat report.md

          cml comment create --target=pr --publish report.md
