name: "Codecheck"

on:
  push:
    branches: [ master, main, feat/github-actions ]
  pull_request:
    branches: [ master, main ]

jobs:
  codecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10 with pip cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install ruff
        run: pip install ruff

      - name: Run ruff check
        run: ruff check .

      - name: Install mypy
        run: pip install mypy

      - name: Run mypy
        run: mypy .
