# .github/workflows/deploy-ui.yaml
name: Deploy Gradio App to Hugging Face

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone --depth=1 https://huggingface.co/spaces/alzlaz/diabetes-predictor-ui space
          rsync -av --delete diabetes_predictor_ui/ space/
          cd space
          git add .
          git commit -m "Auto-deploy from GitHub Actions" || echo "No changes"
          git push https://alzlaz:$HF_TOKEN@huggingface.co/spaces/alzlaz/diabetes-predictor-ui HEAD:main


