# .github/workflows/deploy-ui.yaml
name: Deploy Gradio App to Hugging Face

on:
  push:
    branches: 
      - '**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install git-lfs
          git lfs install

      - name: Clone Hugging Face Space (full depth)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git clone https://$HF_TOKEN@huggingface.co/spaces/alzlaz/diabetes-predictor-ui space

      - name: Copy UI files and push
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          rsync -av --delete diabetes_predictor_ui/ space/
          cd space
          git add .
          git commit -m "Auto-deploy from GitHub Actions" || echo "No changes"
          git push --force https://alzlaz:$HF_TOKEN@huggingface.co/spaces/alzlaz/diabetes-predictor-ui HEAD:main

          



