name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches: [main, phase3/actions]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push trainer image
        run: |
          docker build -f dockerfiles/train_model.dockerfile -t alzlaz1/trainer-image:latest .
          docker push alzlaz1/trainer-image:latest

      - name: Build and push predictor image
        run: |
          docker build -f dockerfiles/predict_model.dockerfile -t alzlaz1/predictor-image:latest .
          docker push alzlaz1/predictor-image:latest
