name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches: [main, phase3/actions]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push trainer image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/train_model.dockerfile
          push: true
          tags: alzlaz1/trainer-image:latest

      - name: Build and push predictor image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/predict_model.dockerfile
          push: true
          tags: alzlaz1/predictor-image:latest
